blank_issues_enabled: false
contact_links:
  - name: ğŸ’¡ Feature Request
    url: https://github.com/obliquul/obliquul.com/discussions/categories/feature-requests
    about: Suggest an idea for this project..
  - name: ğŸŸï¸ Support Ticket
    url: https://github.com/obliquul/obliquul.com/discussions/categories/support-tickets
    about: Talk to us if you need help..
